[build]
publish = "frontend/e-health-wallet/dist/e-health-wallet"
command = "cd frontend/e-health-wallet && npm install && ng build --configuration production"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
