[build]
base = "frontend/e-health-wallet"
command = "npm install && ng build --configuration production"
publish = "dist/e-health-wallet/browser"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
